name: skill_colab
version: 1.1.0+63
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  audioplayers: ^5.2.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  change_app_package_name: ^1.1.0
  chips_choice: ^3.0.1
  cloud_firestore: ^4.9.2
  # connectivity_plus: ^4.0.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^3.0.0
  dartz: ^0.10.1
  dio: ^5.4.0
  dot_navigation_bar: ^1.0.2
  emoji_picker_flutter: ^1.6.3
  encrypt: ^5.0.3
  enum_to_string: ^2.0.1
  file_picker: ^6.1.1
  filter_list: ^1.0.2
  firebase_auth: ^4.15.0
  firebase_core: ^2.16.0
  firebase_messaging: ^14.7.8
  firebase_storage:
  fl_chart: ^0.64.0
  flutter_facebook_auth: ^6.0.3
  flutter_local_notifications: ^16.2.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.5.4
  flutter_slidable: ^3.0.1
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  flutter_typeahead: ^5.0.1
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  giphy_get: ^3.5.2
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.6
  google_sign_in_ios: ^5.6.5
  http: ^1.1.0
  # html: ^0.15.0
  image: ^4.1.3
  image_picker: ^1.0.4
  image_stack: ^2.1.1
  injectable: any
  intl: ^0.18.0
  keyboard_emoji_picker: ^1.0.3
  loop_page_view: ^1.2.5
  lottie: ^2.6.0
  material_tag_editor: ^0.1.2
  path: ^1.8.3
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.2.0-beta-1
  pull_to_refresh: ^2.0.0
  readmore: ^2.2.0
  record: ^5.0.5
  rxdart: ^0.27.7
  screenshot: ^2.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^5.0.0
  textfield_tags: ^2.0.2
  transparent_image: any
  uri_to_file: ^1.0.0
  url_launcher: ^6.2.2
  uuid: ^4.1.0
  video_player: ^2.8.1
  video_thumbnail: ^0.5.3
  marquee:
  widget_zoom: ^0.0.3
  webview_flutter: ^4.5.0
  flutter_quill: ^8.6.0
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html: ^0.14.11
  syncfusion_flutter_datepicker: ^24.2.3
  quill_html_editor: ^2.2.0
  shimmer: ^3.0.0
  quill_html_converter: ^9.3.1
  in_app_notification: ^1.1.2
  device_preview: ^1.1.0
  html: ^0.15.0
  fleather: ^1.14.1
  quill_delta: ^3.0.0-nullsafety.2
  avatar_stack: ^1.2.0
  palette_generator: ^0.3.3+3
  chewie:
  uni_links: ^0.5.1

  
dev_dependencies: 
  build_runner: any
  flutter_test: 
    sdk: flutter
  freezed: any
  json_annotation: any
  json_serializable: any

  lints: ^2.0.0
  pubspec_dependency_sorter: ^1.0.4
  
flutter: 
  assets: 
    - assets/languages/
    - assets/images/
    - assets/droplets/
    - assets/long_images/
    - assets/icons/
    - assets/animations/
  fonts: 
    - 
      family: Inter
      fonts: 
        - 
          asset: fonts/Inter-Regular.ttf
        - 
          asset: fonts/Inter-SemiBold.ttf
          weight: 500
        - 
          asset: fonts/Inter-Bold.ttf
          weight: 700
        - 
          asset: fonts/Inter-ExtraBold.ttf
          weight: 900
  uses-material-design: true
